### ISSUE TITLE
funcr

### ISSUE THREAD

**Issue by ben-williams** [jmcastagnetto/ggplot2_themes_in_github#3]
Here is another theme if you are so inclined
https://github.com/ben-williams/funcr

**Comment by jmcastagnetto** [comment]
Sorry for the extremely long time getting back to you on this. Was looking at this repo after ages, because I wanted to add a auto-rendering action. 

The list is compiled using the searching for the tags and description for repos, so I just checked (https://github.com/search?q=ggplot2+theme+funcr) and yours does not appear in the search. Perhaps, adding tags or the text `ggplot2` and `theme` in the description will work, so it will be picked next time the github action runs (next Sunday).

Will close this issue for now. Feel free to reopen it again in case you think it is needed.
